### ISSUE TITLE
Возможно ли продление  токена без СМС

### ISSUE THREAD

**Issue by maxisoft-git** [QIWI-API/qiwi-wallet-personal-docs#1]
Возможно ли будет продление ранее выданного токена без повторного запроса СМС, или же возможно offline токена, для использования в web приложениях ?

**Comment by garmd** [comment]
Пока токен живет 180 дней и требует перевыпуска на https://qiwi.com/api с вводом кода из смс.
Что вы имеете в виде по offline токеном?

**Comment by maxisoft-git** [comment]
Имелось ввиду как раз возможность продлять токен без СМС, или получить токен без ограничения (offline).
