### ISSUE TITLE
Сломанные права доступа

### ISSUE THREAD

**Issue by vasinkd** [QIWI-API/qiwi-wallet-personal-docs#10]
Выбирая различные комбинации прав доступа получаю следующие результаты:
1) Только просмотр истории - доступна история и общая информация (что, кстати, адекватно, т.к. для просмотра истории нужно запоминать еще и мобильный)
2) История и баланс - доступна история и общая информация; баланс не доступен

UPD: 3. Общая информация и баланс - доступны история, общая информация И баланс

Неочевидное поведение, как по мне. Платежи я не пробовал, но если они тоже работают при отсутствии прав доступа у токена, то это совсем печально.

**Comment by garmd** [comment]
Спасибо, что обратили внимание, проблема нам известна. Работаем над исправлением.
