### ISSUE TITLE
Некорректное название поля в документации

### ISSUE THREAD

**Issue by vasinkd** [QIWI-API/qiwi-wallet-personal-docs#11]
В документации в разделе "История платежей" поле data[].account обозначено как "Номер счета получателя", хотя скорее это "Номер счета контрагента", там может быть и получатель, и отправитель в зависимости от типа операции

**Comment by garmd** [comment]
Да, вы правы. Поправим.
Для входящих транзакций - это в data[].account может быть номер отправителя, id терминала или наименование агента пополнения кошелька, например, "Альфа-банк".

**Comment by mmmikhail** [comment]
Done
