### ISSUE TITLE
Автозаполнение платежных форм – выбор способа оплаты

### ISSUE THREAD

**Issue by 1F47E** [QIWI-API/qiwi-wallet-personal-docs#13]
1.

В методе Автозаполнение платежных форм очень не хватает возможности выбрать сразу метод оплаты, который появился в новой форме.

Например – выбрать за пользователя способ оплаты Картой.
И проскролить экран сразу на ввод карты + фокус на поле ввода карты.

Результат – пользователь переходит по ссылке и сразу переходит к вводу данных карты.

2.

Добавить возможность блокировать поля получателя платежа. 
Номер Кошелька получателя, Комментарий, Сумма – readonly

**Comment by mmmikhail** [comment]
Номер кошелька сейчас по умолчанию readonly

**Comment by mmmikhail** [comment]
1. 
можно использовать вызов p2p платежной формы после выставления счета на оплату p2p.qiwi.com https://developer.qiwi.com/ru/bill-payments/?shell#option

2.
используйте параметр `blocked` - `..&blocked[1]=comment&blocked[2]=sum`
