### ISSUE TITLE
Оплата выставленных счетов

### ISSUE THREAD

**Issue by nikitao23** [QIWI-API/qiwi-wallet-personal-docs#2]
Есть ли возможность через API узнавать о появлении выставленных счетов и оплачивать их ?
Спасибо

**Comment by garmd** [comment]
Пока этого нет, изучим возможность добавления.

**Comment by gkonnov** [comment]
@nikitao23 мы, кстати, запустили в мае. Видели? :)
https://developer.qiwi.com/ru/qiwi-wallet-personal/index.html#section-7
