### ISSUE TITLE
Лимиты кошелька

### ISSUE THREAD

**Issue by candro** [QIWI-API/qiwi-wallet-personal-docs#20]
Предлагаю добавить актуальные лимиты кошелька и раскрыть возможные варианты лимитов.

GET https://edge.qiwi.com/qw-limits/v1/persons/79628647452/actual-limits

На данный момент это (query params):
```
types[0]: REFILL
types[1]: TURNOVER
types[2]: PAYMENTS_PROVIDER_PAYOUT
types[3]: PAYMENTS_P2P
types[4]: PAYMENTS_PROVIDER_INTERNATIONALS
types[5]: WITHDRAW_CASH
```

**Comment by mmmikhail** [comment]
Добавлено описание API лимитов
