### ISSUE TITLE
Настройки безопасности

### ISSUE THREAD

**Issue by candro** [QIWI-API/qiwi-wallet-personal-docs#23]
Дайте пожалуйста настройки безопасности из апи. Старый интерфейс пора закрывать уже через  tgsts токены.

**Comment by mmmikhail** [comment]
Вы про это? 
![image](https://user-images.githubusercontent.com/22835105/82205104-b4cac180-990e-11ea-843b-e7a74bbd8dbc.png)

**Comment by candro** [comment]
Расширенные настройки безопасности

**Comment by mmmikhail** [comment]
В разработке, следите за обновлениями

**Comment by candro** [comment]
Отличная новость, спасибо!
