### ISSUE TITLE
Никнейм кошелька

### ISSUE THREAD

**Issue by candro** [QIWI-API/qiwi-wallet-personal-docs#24]
Добавьте в документацию, что можно получать инфу про свой никнейм через:

> GET: https://edge.qiwi.com/qw-nicknames/v1/persons/{PESON_ID}/nickname

**Comment by candro** [comment]
json в ответ скажет вам что-то вроде:

```json
{"nickname":null,"canChange":true,"canUse":false,"description":""}
```

**Comment by mmmikhail** [comment]
done
