### ISSUE TITLE
Оплата выставленных счетов

### ISSUE THREAD

**Issue by AgapovAlexsey** [QIWI-API/qiwi-wallet-personal-docs#4]
Когда появится возможность через API узнавать о появлении выставленных счетов и оплачивать их ?
Обещали определиться еще в октябре.

**Comment by gkonnov** [comment]
Добрый день. Моя команда работает над этим. В 1Q 2018 года должно появиться. Не раскажете подробнее, как планируете использовать это API? Тогда мы сможем сделать его лучше.

**Comment by AuroRacing** [comment]
Уже 1Q 2018 подходит к концу) А мы все ждем(

**Comment by nikitao23** [comment]
Очень ждем)

**Comment by gkonnov** [comment]
@nikitao23  @AuroRacing @AgapovAlexsey мы, кстати, запустили в мае. Видели? :)
https://developer.qiwi.com/ru/qiwi-wallet-personal/index.html#section-7
