### ISSUE TITLE
Поиск по номеру клиентской транзакции

### ISSUE THREAD

**Issue by ntfnd404** [QIWI-API/qiwi-wallet-personal-docs#5]
Очень частно нужно запросить данные по номеру клиентской транзакции так как именно этот номер фигурирует в бумажном чеке (trmTxnId).. В API есть метод которые отдает данные по txnId, но он не подходит так как изначально у нас нет этого номера.. Получается надо сначала получить список платежей со всеми данными, потом в нужной записи вычленить txnId и по нему получить запись с помощью метода отдающего по транзакции.Зачем? если в списке уже есть нужные данные?!!! добавьте пожалуйста поиск по trmTxnId.

**Comment by garmd** [comment]
в истории кошелька нет и не планируется id с чеков с терминала
id транзакции у того кто отправляет деньги и получает будет совпадать только в одном случае - при переводе с кошелька на кошелек
