### ISSUE TITLE
Original Amount and Currency in transaction history

### ISSUE THREAD

**Issue by Zubaloo** [QIWI-API/qiwi-wallet-personal-docs#6]
Здравствуйте,

есть ли в планах добавить в информацию о транзакциях сумму и валюту в которой транзакция инициировалась? Например для платежей по пластиковым картам Qiwi это будет валюта той страны в которой выставили счёт и произошла оплата. Такая информация сейчас есть на сайте в отчётах по картам, но было бы хорошо иметь её и в API в списке транзакций

**Comment by garmd** [comment]
это весьма специфический пример, будет здорово, если вы отправите пример транзакции, по которой вам недостаточно информации в API.
так как здесь нельзя упоминать данные клиентов, лучше письмом на api_help@qiwi.com
