### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by 1F47E** [QIWI-API/qiwi-wallet-personal-docs#8]
Сейчас для того, чтобы узнать что пришел новый платеж – необходимо периодически дергать API входящих платежей (**polling**).

**Push** принцип существенно разгрузит ваш сервер от лишних запросов, а также поможет разработчикам создавать решения, которые будут быстрее реагировать на оплату.

Как самый просто вариант – это **webhook** на endpoint клиента (указанный через отдельный метод) с телом новой транзакции.

Хороший пример – Telagram Bot API https://core.telegram.org/bots/api#getting-updates

**Comment by garmd** [comment]
Да, у нас это в планах на разработку и тестирование на апрель-май.
Если вы не против раннего уведомления о готовности, оставьте ваш email здесь или напишите на api_help@qiwi.com
