### ISSUE TITLE
Лимиты

### ISSUE THREAD

**Issue by vasinkd** [QIWI-API/qiwi-wallet-personal-docs#9]
Нужен удобный способ, чтобы узнать доступные для перевода объемы денежных средств. Насколько я понимаю, текущие объемы по переводам можно было бы узнавать с помощью раздела "Статистика платежей", но возникает вопрос: что делать, если были переводы в различной валюте?

**Comment by garmd** [comment]
Пока удобного способа нет, есть неудобный - переводить самостоятельно.
Пока этой задачи в планах нет, возможно, вернемся к ней в конце года.
